services:
  # Backend API service
  - type: web
    name: newsy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn mcp.v1.src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SERPAPI_API_KEY
        sync: false
      - key: CLARIFAI_API_KEY
        sync: false
    healthCheckPath: /health
